### PR TITLE
Fix Namespace not specified

### PR DESCRIPTION
**Pull request by muhmmedAbdelkhalikElabd**
ScreenShot-TFw6cYuH

> To fix this issue
Add  namespace `"com.excprotection.payment"` in `android/build.gradle`

### CODE REVIEW

**Comment by ahmedelkhyary** [comment]
> ScreenShot-TFw6cYuH
> 
> > To fix this issue
> > Add  namespace `"com.excprotection.payment"` in `android/build.gradle`

which flutter SDK version used that appear this error

**Comment by muhmmedAbdelkhalik** [comment]
> > ScreenShot-TFw6cYuH
> > > To fix this issue
> > > Add  namespace `"com.excprotection.payment"` in `android/build.gradle`
> 
> which flutter SDK version used that appear this error and Gradle version

Last SDK `3.24.3`

**Comment by muhmmedAbdelkhalikElabd** [comment]
> > ScreenShot-TFw6cYuH
> > > To fix this issue
> > > Add  namespace `"com.excprotection.payment"` in `android/build.gradle`
> 
> which flutter SDK version used that appear this error and Gradle version

Last SDK `3.24.3`

**Comment by ahmedelkhyary** [comment]
> Gradle version

 Gradle version ?

**Comment by muhmmedAbdelkhalikElabd** [comment]
> > Gradle version
> 
> Gradle version ? @muhmmedAbdelkhalikElabd

```
Gradle: 8.3
Kotlin: 1.9.0
Groovy: 3.0.17
```

**Comment by ahmedelkhyary** [comment]
> > > Gradle version
> > 
> > 
> > Gradle version ? @muhmmedAbdelkhalikElabd
> 
> ```
> Gradle: 8.3
> Kotlin: 1.9.0
> Groovy: 3.0.17
> ```

Thanks @muhmmedAbdelkhalikElabd

**Pull request merged**
